- name: variables
  hosts: local host
  vars:
   course: "devops"
   duration: "120hrs"
  tasks:
  - name: print override information
    vars:
     course: "terraform"
    ansible.builtin.debug:
     msg : "hi iam learning {{course}}and the duration is {{duration}}" 


  - name: print information
    ansible.built.in.debug:
     msg:hi we are learning {{course}} and the duration is {{duration}}  
