- name: variables from files
  hosts: localhosts
  vars_file:
  - vars.yaml
  tasks: 
  - name: print variables from files
    ansible.builtin.debug:
     msg: "Hi My Name is {{name}} and I am learning {{course}} and duration is {{duration}}"