- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks: 
  - name: print variables from files
    ansible.builtin.debug:
     msg: "Hi My name is {{name}} and I am learning {{course}} and duration is {{duration}}"