- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - prompt: please enter your user name
    name: USERNAME
    private: false

  - prompt: please enter your password
    name: PASSWORD
    private: true 
  tasks:
  - name: Print Prompt information
    ansible.builtin.debug:
     msg: "Hi username: {{USERNAME}}. Password is {{PASSWORD}}"
