- name: variables from inventory
  hosts: localhost
  tasks:
  - name: inventory variables
    ansible.builtin.debug:
     msg: "hi my name is {{name}} and i am learning {{course}} and the duration is {{duration}}"