- name: Default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "The course iam learing is {{course | default ('ansible')}} "

- name: upper case letters
  hosts: localhost
  vars:
   wishes: "hello good morning this is sukesh"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{wishes | upper}}"

- name: upper case letters
  hosts: localhost
  vars:
   wishes: "HELLO GOOD MORNING THIS IS SUKESH"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{ wishes | lower }}"     

- name: Remove duplicate numbers
  hosts: localhost
  vars:
   numbers: [1, 2, 3, 4, 5, 5, 5, 6, 7, 8, 8, 9]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

- name: minimum and maximum
  hosts: localhost
  tasks:
  - name: min and max
    vars:
     ages: [25, 35, 22, 72, 92, 82]
    ansible.builtin.debug:
     msg: min age is {{ages | min }} and max {{ages | max}}

- name: converting dictionary or maps in to items/list
  hosts: localhost
  vars:
   my_dict:  #this is called dictionary or map or key/value pairs
    course: devops
    trainer: self
    duration: 120hrs
  tasks:
  - name: befor converting
    ansible.builtin.debug:
     msg: "befor converting: {{ my_dict }}"

  - name: after converting
    ansible.builtin.debug:
     msg: "after converting to items: {{ my_dict | dict2items }}"     
 
- name: converting items in to dictionary
  hosts: localhost
  vars:
   my_list:
   - {'key': 'course', 'value': 'devops'}
   - {'key': 'trainer', 'value': 'self'}
   - {'key': 'duration', 'value': '120hrs'}
  tasks:
  - name: befor converting
    ansible.builtin.debug:
     msg: "befor converting: {{ my_list }}"

  - name: after converting
    ansible.builtin.debug:
     msg: "after converting to items: {{ my_list | items2dict }}"