- name: Remove Packages
  hosts: localhost
  tasks:
  - name: remove some packages
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} #items
    - { name: 'nginx',  state: 'absent'}
    - { name: 'postfix', state: 'absent'}